use Retaildb

--Data Prepration and Understanding

select top 1 * from Customer
select top 1 * from prod_cat_info
select top 1 * from transactions

--1.What is the total number of rows in each of the 3 tables in the database.
   
   Select COUNT(*) as cnt from Customer
   union
   Select COUNT(*) as cnt from prod_cat_info
   union
   Select COUNT(*) as cnt from Transactions

--2.What is the total number of transactions that have a return?

   Select COUNT(distinct(transaction_id)) as tot_trans from Transactions
   where Qty < 0

--3.
  
  Select CONVERT(date,tran_date,105) as tran_dates from Transactions

--4.What is the Time Range of the transaction data available for analysis? output of the number of days, months and year simultaneously in different columns.

  Select DATEDIFF(YEAR,MIN(CONVERT(date,tran_date,105)),MAX(CONVERT(date,tran_date,105))) As diff_years,
  DATEDIFF(MONTH,MIN(CONVERT(date,tran_date,105)),MAX(CONVERT(date,tran_date,105))) As diff_months,
  DATEDIFF(DAY,MIN(CONVERT(date,tran_date,105)),MAX(CONVERT(date,tran_date,105))) As diff_days
  from Transactions

--5.Which Product category does the sub-category 'DIY" belong to?

   Select prod_cat,prod_subcat from prod_cat_info
   where prod_subcat = 'DIY'

--. Data Analysis

select top 1 * from Customer
select top 1 * from prod_cat_info
select top 1 * from transactions

--1.Which Channel is most frequently used for transactions?
   
   Select top 1 store_type,COUNT(*) as cnt from Transactions
   group by Store_type
   order by cnt desc

--2.What is the count of male and female customers in the database?
   
   Select gender , COUNT(*) as cnt from Transactions
   where gender is not null
   group by Gender
   
--3.From Which city do we have the maximum number of customers and how many?
   
   Select top 1 city_code, COUNT(*) as cnt from Customer
   group by city_code
   order by cnt desc

--4.How many sub-categories are there under the Books category?

   Select prod_cat, prod_subcat from prod_cat_info
   where prod_cat = 'Books'

--5.What is the maximum quantity of products ever orered?

   Select prod_cat_code, max(qty) as max_prod from Transactions
   group by prod_cat_code

--6.What is the total revenue generated in categories Electronic and Books?

   Select SUM(Cast (total_amt as float)) as net_revenue from prod_cat_info as t1
   join Transactions as t2
   on t1.prod_cat_code = t2.prod_cat_code AND t1.prod_cat_code = t2.prod_subcat_code
   where prod_cat = 'Book' OR prod_cat = 'Electronic'
    
	use Retaildb
--7.How many Customer have > 10 transactions with us,excluding return?

   Select COUNT(*) as tot_cust from (
   Select cust_id , COUNT(distinct(transaction_id)) as cnt_trans from Transactions
   where Qty > 0
   group by cust_id
   having COUNT(distinct(transaction_id)) >10
   ) as t5 

--8.What is the combined revenue earned from the "Electronic" & "Clothing" categories, from "Flagship stores"?

   Select SUM(cast(Total_amt as float)) as combined_revenue from prod_cat_info as t1
   join Transactions as t2
   on t1.prod_cat_code = t2.prod_cat_code AND t1.prod_sub_cat_code = t2.prod_subcat_code
   where  prod_cat in ('Clothing','Electronic') AND Store_type = 'Flagship store' and Qty > 0

--9.What is the total revenue generated from "Male" customer in "Electronic" categories?

   Select prod_subcat, SUM(cast(Total_amt as float)) as tot_revenue from Customer as t1
   join Transactions as t2 
   on t1.customer_Id = t2.cust_id
   join prod_cat_info as t3
   on t2.prod_cat_code = t3.prod_cat_code and t2.prod_subcat_code = t3.prod_sub_cat_code
   where gender = 'M' and prod_cat = 'Electronics'
   Group by prod_subcat
   
   use Retaildb

--10.   What is the percentage of sales and returns by product sub category

    Select t5.prod_subcat, percentage_sales,percentage_returns from (
	Select top 5 prod_subcat, (sum(cast(total_amt as float))//(Select sum(cast(total_amt as float)) as tot_sales from Transactions where Qty > 0) as from prod_cat_info as t1
	from prod_cat_info as t1
	join Transactions as t2
	on t1.prod_cat_code = t2.prod_cat_code And t1.prod_sub_cat_code = t2.prod_subcat_code
	where qty > 0
	group by prod_subcat
	order by ercentage_sales desc
	) as t5
	join
	(
	Select prod_subcat (sum(cast(total_amt as float))/(Select sum(cast(total_amt as float)) as tot_sales from Transactions where qty < 0 )) as percentage_returns
	from prod_cat_info as t1
	join Transactions as t2
	on t1.prod_cat_code = t2.prod_cat_code And t1.prod_sub_cat_code = t2.prod_subcat_code
	where qty < 0
	group by prod_subcat ) t6
	on t5.prod_subcat = t6.prod_subcat

--11 For all customers aged between 25 to 35 year find what is the net total revenue generated by these consumers 

     Select * from (
     Select cust_id, DATEDIFF(year,DOB,max_date) as Age, revenue from (
	 Select cust_id, dob, max(convert(date, tran_date,105)) as max_date , sum(cast(total_amt as float)) as revenue from Customer as t1
	 join Transactions as t2
	 on t1.customer_Id = t2.cust_id
	 where Qty > 0 
	 group by cust_id , DOB
	 ) as A
	        ) as B
     Where Age between 25 and 35
	                              ) as C
	 join (
	 Select cust_id, CONVERT(date, tran_date, 105) as tran_date
	 from Transactions
	 group by cust_id, CONVERT(date,tran_date,105)
	 having CONVERT(date, tran_date,105) >= (Select DATEADD(day, -30,max(convert(date, tran_date,105))) as cutoff_date from Transactions)
	 ) as D
	 on c.cust_id = d.cust_id
	 
--12.
     
	 Select top 1 prod_cat_code, SUM(returns) as tot_returns from (
   
     Select prod_cat_code, CONVERT(date, tran_date, 105) as tran_date , SUM(qty) as Returns
	 from Transactions
	 where Qty < 0
	 group by prod_cat_code, CONVERT(date, tran_date, 105)
	 having CONVERT(date, tran_date,105) >= (select DATEADD(month, -3,max(convert(date, tran_date,105))) as cutoff_date from Transactions)
	 ) as A
	 Group By prod_cat_code
	 order by tot_returns

use Retaildb
--13

    Select Store_type, sum(cast(total_amt as float)) as revenue, sum(qty) as quantity
	from Transactions
	where Qty > 0
	group by Store_type
	order by revenue desc , quantity desc

--14

   Select prod_cat_code , AVG(cast(total_amt as float)) as avg_revenue from Transactions
   where Qty > 0
   group by prod_cat_code
   having AVG(cast(total_amt as float)) >= (Select AVG(cast(total_amt as float)) from Transactions where Qty > 0)

--15

   Select prod_subcat_code, SUM(cast(total_amt as float)) as revenue , AVG(cast(total_amt as float)) as avg_revenue
   from Transactions
   where Qty > 0 and prod_cat_code in (Select top 5 prod_cat_code , SUM(qty) as Quantity from Transactions
                                       where Qty > 0
                                       group by prod_subcat_code
                                       order by Quantity desc )
   
   group by prod_cat_code








   


















